#ifndef PAIRTRADINGSTRATEGY_GLOBAL_H
#define PAIRTRADINGSTRATEGY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PAIRTRADINGSTRATEGY_LIBRARY)
#  define PAIRTRADINGSTRATEGYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PAIRTRADINGSTRATEGYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PAIRTRADINGSTRATEGY_GLOBAL_H
