#ifndef GROUP8STRATEGY_GLOBAL_H
#define GROUP8STRATEGY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GROUP8STRATEGY_LIBRARY)
#  define GROUP8STRATEGYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GROUP8STRATEGYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GROUP8STRATEGY_GLOBAL_H
